//https://ddb-authorization-api.herokuapp.com/
### get user route
GET http://localhost:8090/


### register route
POST http://localhost:8090/api/v1/auth/register
Content-Type: application/json

{
    "email": "patcon1234@gmail.com",
    "username": "patcon1234",
    "password": "12345"
}

### verify-email/verify-account
PATCH http://localhost:8090/api/v1/secondary-auth/account-verification/eyJhbGciOiJSU0EtU0hBMjU2IiwiZXhwIjoiMzAwMDAwIiwiYXVkIjoibG9jYWxob3N0Iiwic3ViIjoiNjJlMDI1ODBhY2FlYjdjMjhkZjkzNTQ5IiwiaXNzIjoidmJvbXMuY29tIiwidGFpIjoiMTY1ODg1NjgzMjcyNCJ9%5EeyJpZCI6IjYyZTAyNTgwYWNhZWI3YzI4ZGY5MzU0OSJ9%5EngFgR4mGM9uLzWQ9sn26GhkRex5C28WXiwMVSSdnJmX00ICJU2QldjAetGs2dQSPr4kRqX_qxgK8CYCTvMtk0IdAabUm34g00JUHRv53GcRBSztvPC-sZ2p4aS_qtOelOw4kpwiVzQ6mVMg1POWTpF5u6NSDuKoNYGrCqLQFbL7V5lTJXqYmakUMmXvxp2QyjuWqaLBgjVdIIpYyKEzV53LTDrOUEjfFN3kP6nafLI1pe5DHocnMR08ytX9P42iNwhADcUAlALdl5s7OWOOnb4zaf6FttYeXUQckUjeBrFvHZ8i_ONnihXh3fKtGNUHbEz-lBlEdoGt0PdiSjAqmeWIl_cXfDPLzpXbiNFSWFTQoFLuRZab3rMfRTSVGK31pWSPTKDWNx7hLj8LQI1R2RPz7Pb0ntY24QsHJgTdolmobxBisFZld86LbcqwFE176syM8aqFwXR4lzsRDwKbdUdRUgtzZvF8AQxPOcCAxk2tCW3MM1vplf_DEW2Cxi3sKtSB-ZHFh7Bx2kREvCs3vcMgMiPU_crmZJ9VFugKP9izb1jKXtrAd3tGXZDvSGZmr2972PbYkh7fpYzIPTgDnIr7FTrsdAdE4GDikMTJZXElApAMv_gPl67SACJYL4zO2_QWdyIMze95cp5SIBOefFK71GyMKCcdbk1kFka6QPqY
Content-Type: application/json


### login route
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "identifier": "pat12",
    "password": "123"
}

### update user route
PUT http://localhost:8080/api/v1/user/60a8084883abdd11b4e0d8f2
Content-Type: application/json

{
    "email": "p@p.com"
}

### delete route
DELETE  http://localhost:8080/api/v1/auth/logout
Content-Type: application/json


### login pin route
PUT http://localhost:8080/api/v1/secondary-auth/login-pin/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTdkMDkyNzBjNWVjM2NmNDU0NjdiMSIsImV4cGlyZXMiOjMwMDAwMCwiZXhwaXJlRGF0ZSI6IjIwMjEtMDUtMjFUMTc6MDQ6NTUuNTY2WiIsImlzcyI6ImxvY2FsaG9zdCIsImlhdCI6MTYyMTYxNjM5NSwiZXhwIjoxNjIxOTE2Mzk1fQ.ZjBZbA3H2KAYwKjybLLvEUqBM2LQYlEtW-PS9m5oYd4
Content-Type: application/json

{
    "pin": "185074"
}

### reset route
PUT http://localhost:8080/api/v1/auth/forgot-password
Content-Type: application/json

    {
        "identifier": "eee34"
    }

### reset pin route
PUT http://localhost:8080/api/v1/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTdmZDlmMTQwNWZjNjRmODBjMGUyYyIsImV4cGlyZXMiOjMwMDAwMCwiZXhwaXJlRGF0ZSI6IjIwMjEtMDUtMjFUMTk6MTA6MDUuMTUzWiIsImlzcyI6ImxvY2FsaG9zdCIsImlhdCI6MTYyMTYyMzkwNSwiZXhwIjoxNjIxOTIzOTA1fQ.5ILWFlFvvbW8AIms5IZw7KSoPVqlQ1KM57cnkc6tVow
Content-Type: application/json

{
    "password": "12"
}

### login route
PUT http://localhost:8080/api/v1/secondary-auth/reset-pin/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTdmZDlmMTQwNWZjNjRmODBjMGUyYyIsImV4cGlyZXMiOjMwMDAwMCwiZXhwaXJlRGF0ZSI6IjIwMjEtMDUtMjFUMTk6MDk6NDEuMTQxWiIsImlzcyI6ImxvY2FsaG9zdCIsImlhdCI6MTYyMTYyMzg4MSwiZXhwIjoxNjIxOTIzODgxfQ.f3KJkjcoH91DpipWj4vLIq2kglsgVulnJ4Q6FkAGthc
Content-Type: application/json

{
    "pin":"877400"
}

### login route
PUT http://localhost:8080/api/v1/secondary-auth/verify-pin/
Content-Type: application/json

### login route
PUT http://localhost:8080/api/v1/secondary-auth/reset-pin/
Content-Type: application/json

### login route
PUT http://localhost:8080/api/v1/secondary-auth/phone-pin/
Content-Type: application/json


### verify phone route
PUT http://localhost:8080/api/v1/secondary-auth/verify-phone/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTgwODQ4ODNhYmRkMTFiNGUwZDhmMiIsImV4cGlyZXMiOjMwMDAwMCwiZXhwaXJlRGF0ZSI6IjIwMjEtMDUtMjFUMjE6NTQ6MTguMDc3WiIsImlzcyI6ImxvY2FsaG9zdCIsImlhdCI6MTYyMTYzMzc1OCwiZXhwIjoxNjIxOTMzNzU4fQ.Th4rkGyTvypwJ5P-2_O6jqua1iSU2NjxG9tkJXTlFQs
Content-Type: application/json

{
    "pin": "446485"
}



### Get User
GET http://localhost:8080/api/v1/user/60a85e3cba01b30015b706e9
Content-Type: application/json



### Get User
DELETE http://localhost:8080/api/v1/user/60a85e3cba01b30015b706e9
Content-Type: application/json
